### ISSUE TITLE
panic: read /dev/stdin: resource temporarily unavailable

### ISSUE THREAD

**Issue by boris-kuz** [antonmedv/llama#16]
Hey there.

On OSX 11.4 (Intel), I get the following error after navigating to a file, editing it with Neovim, and exiting Neovim:

```
panic: read /dev/stdin: resource temporarily unavailable

goroutine 1 [running]:
main.main()
	/Users/anton/dev/llama/main.go:66 +0x277
```

**Comment by antonmedv** [comment]
Yeah, can’t do much. This issues is blocking https://github.com/charmbracelet/bubbletea/issues/171

**Comment by boris-kuz** [comment]
Ah, that's a shame. Thanks for responding so quickly! Also, awesome project, love using llama. :)

**Comment by meowgorithm** [comment]
The appropriate functionality has been implemented in Bubble Tea and Llama's been updated accordingly in https://github.com/antonmedv/llama/pull/19, which I believe resolves this issue.
