### ISSUE TITLE
Asset names are wrong in v1.1.1

### ISSUE THREAD

**Issue by suzuki-shunsuke** [antonmedv/llama#28]
https://github.com/antonmedv/llama/releases/tag/v1.1.1

<img width="351" alt="image" src="https://user-images.githubusercontent.com/13323303/202691203-7b67f3c6-f092-4cf0-a3b7-613a90f70904.png">

Asset names are wrong.
Not [fx](https://github.com/antonmedv/fx) but llama.

**Comment by antonmedv** [comment]
Fixed.
