### ISSUE TITLE
config file location?

### ISSUE THREAD

**Issue by swapneelb** [antonmedv/llama#33]
Could you please add more instructions on how to create a config file?
I want to change the default editor to nano.

**Comment by antonmedv** [comment]
Just set env var LLAMA_EDITOR=nano

**Comment by swapneelb** [comment]
How? I am on a mac. I don’t know where to set the env var.

**Comment by antonmedv** [comment]
In bash_profile

**Comment by swapneelb** [comment]
okay, got it. I will add this to my .zshrc file. thank you.

**Comment by swapneelb** [comment]
That did not work. In my .zshrc file, i added LLAMA_EDITOR=nano
and the files are still opening in vim

**Comment by antonmedv** [comment]
¯\\\_(ツ)_/¯

**Comment by Betelgeuse1** [comment]
Didn't you said in #5 that you were now using `$EDITOR` instead of `$LLAMA_EDITOR` ?

**Comment by antonmedv** [comment]
Both are used.
