### ISSUE TITLE
Exit with ESC does not change folders

### ISSUE THREAD

**Issue by mike-ward** [antonmedv/llama#39]
When exiting with ESC it prints the folder but does not change folders.

![image](https://user-images.githubusercontent.com/567927/203568544-393be1b6-e4e6-47b6-b0c5-7ce078f0fa1e.png)

Windows 10, command terminal or power shell.

**Comment by antonmedv** [comment]
Please read readme.

**Comment by mike-ward** [comment]
Maybe you should read your own README. Here let me paste the relevant bit here to save you time.

![image](https://user-images.githubusercontent.com/567927/203576817-68e8d52c-f6c3-4373-943f-66598efcd1ab.png)

**Comment by antonmedv** [comment]
![1955FCBE-D063-44BC-9BE9-68AD26ECBD20](https://user-images.githubusercontent.com/141232/203580561-e1736e69-9d5c-4a22-b7bb-6b28d33700e5.jpeg)

**Comment by mike-ward** [comment]
Sorry. I read it twice and went right by it.
