### ISSUE TITLE
No highlighting when run in screen and $TERM=screen

### ISSUE THREAD

**Issue by smpaine** [antonmedv/llama#42]
When run under a screen session, there is no highlighting, so the currently selected item is unknown. Appears that screen sets the "TERM" environment variable to "screen" which appears to cause the issue.

llama running under bash, not in a screen session; TERM is xterm-256color:
![llama_in_bash](https://user-images.githubusercontent.com/639957/203654496-1db374d8-be43-4b68-b8d4-510883b65bf0.png)

llama running under bash, while in a screen session; TERM is screen. Overriding TERM variable with xterm-256color resolves the issue.
![llama_in_bash_in_screen_session](https://user-images.githubusercontent.com/639957/203654556-784e6c5d-729f-4b7d-b088-ab73ed377351.png)

System is FreeBSD 13.1

**Comment by antonmedv** [comment]
I guess this is how bubbletea is working. 

Better to open an issue at https://github.com/charmbracelet/bubbletea
