### ISSUE TITLE
Exit with cd not working

### ISSUE THREAD

**Issue by s-wheels** [antonmedv/llama#47]
Exit with cd is not working on Apple M1 chip - Ventura 13.0.1 in Oh My Zsh. 

<img width="105" alt="image" src="https://user-images.githubusercontent.com/44038032/203779760-7fcc69a1-c620-476c-8073-c5120664a336.png">

**Comment by antonmedv** [comment]
Please read readme.

**Comment by s-wheels** [comment]
Ok thanks, working now - I suggest altering your README to 

Step 1: Install


Step 2: Function

The first time I skim read this and assumed the function was relating to a binary install only.

**Comment by antonmedv** [comment]
Steps steps seems okay
