### ISSUE TITLE
go get soon to be deprecated for installing

### ISSUE THREAD

**Issue by christophberger** [antonmedv/llama#6]
Hint - `go get` currently requires a `@version` suffix when used outside the module dir, e.g.  `go get github.com/antonmedv/llama@latest`. With Go 1.18 `go get` will be replaced by `go install` for installing Go binaries from their module path. You might want to change the readme accordingly.

See [Deprecation of 'go get' for installing executables - go.dev](https://go.dev/doc/go-get-install-deprecation) for details. 

A nice tool BTW!

**Comment by antonmedv** [comment]
Fixed
